on:
  push:
    tags:
      - 'ver*'

name: Release
run-name: Release ${{ github.ref }}

jobs:
  build:
    name: Build and upload
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      - name: Build release
        run: ./build_release.sh
      - name: Get annotation
        id: tag-data
        run: |
          {
            echo 'annotation << EOF'
            git for-each-ref "${GITHUB_REF}" --format '%(contents)'
            echo 'EOF'
          } >> "${GITHUB_OUTPUT}"
      - name: Publish release
        uses: softprops/action-gh-release@v2
        with:
          # make_latest: true
          draft: true
          body: ${{ steps.tag-data.outputs.annotation }}
          files: |
            dist/qspgui_win32.zip
