on:
  push:
    tags: 'v*'

name: Release
run-name: Release ${{ github.ref }}

jobs:
  build:
    name: Build and upload
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      - name: Build release
        run: ./build_release.sh
      - name: Publish release
        uses: softprops/action-gh-release@v2
        with:
          # make_latest: true
          draft: true
          files: |
            dist/qspgui_win32.zip
